services:
  - type: web
    name: checklists
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn app_checklist.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: POSTGRES_LOCALLY
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
