# Generated by Django 5.1.7 on 2026-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0022_formsharelink_formpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankquestion',
            name='question_type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('paragraph', 'Paragraph'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('linear_scale', 'Linear Scale'), ('date', 'Date'), ('time', 'Time'), ('pass_fail', 'Pass / Fail / N/A')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gquestion',
            name='question_type',
            field=models.CharField(choices=[('short_text', 'Short Text'), ('paragraph', 'Paragraph'), ('multiple_choice', 'Multiple Choice'), ('checkbox', 'Checkboxes'), ('dropdown', 'Dropdown'), ('linear_scale', 'Linear Scale'), ('date', 'Date'), ('time', 'Time'), ('pass_fail', 'Pass / Fail / N/A')], max_length=20),
        ),
    ]
