# Generated by Django 5.1.7 on 2026-04-15 23:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def ensure_avatar_url(apps, schema_editor):
    """Add avatar_url column to UserProfile only if it doesn't already exist."""
    from django.db import connection

    with connection.cursor() as cursor:
        existing = set(connection.introspection.table_names(cursor))
    if 'checklist_userprofile' not in existing:
        return

    with connection.cursor() as cursor:
        cols = {c.name for c in connection.introspection.get_table_description(cursor, 'checklist_userprofile')}
    if 'avatar_url' not in cols:
        schema_editor.add_field(
            apps.get_model('checklist', 'UserProfile'),
            apps.get_model('checklist', 'UserProfile')._meta.get_field('avatar_url'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0024_userprofile_emailverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_avatar_url, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userprofile',
                    name='avatar_url',
                    field=models.URLField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
