# Generated by Django 5.1.7 on 2026-04-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0025_settings_avatar_emailchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
    ]
